name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run lint check
        run: npm run lint